name: Check Code Example Directives

on:
    pull_request:
        paths:
        - "source/**"

jobs:
    search_code_directives:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:  
            fetch-depth: 0  # Fetch all history so we can access 'main' or the base branch.  
  
        - name: Fetch base branch  
          run: git fetch origin ${{ github.base_ref }} --depth=1 

        - name: Search for undesired directives
          run: |
            strings_to_search=('.. code-block::' '.. code::')
            errors=""  
            
            # Get a list of changed files  
            changed_files=$(git diff --name-only origin/${{ github.base_ref }}...${{ github.sha }})  
              
            for file in $changed_files; do  
              # Extract new lines for each file, ignoring context lines and file headers  
              new_lines=$(git diff origin/${{ github.base_ref }}...${{ github.sha }} -- "$file" | grep '^+' | grep -v '^\+\+\+')  
      
              # Check each string in new lines  
              for search_string in "${strings_to_search[@]}"; do  
                if echo "$new_lines" | grep -q "$search_string"; then  
                  errors="$errors\nFile '$file' contains '$search_string'"  
                fi  
              done  
            done
      
            if [ ! -z "$errors" ]; then  
              echo -e "Errors found:\n$errors"
              echo "Please replace these directives with '.. literalinclude::' or '.. io-code-block::'"
              echo "For more information, refer to the wiki: [link here]"
              exit 1  
            else  
              echo "No errors found."  
            fi
