name: Check Code Example Directives

on:
    pull_request:
        paths:
        - "source/**"

jobs:
    search_code_directives:
        runs-on: ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v3
          with:  
            fetch-depth: 0  # Fetch all history so we can access 'main' or the base branch.  
  
        - name: Fetch base branch  
          run: git fetch --no-tags origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

        - name: Get list of changed files
          id: changed_files
          run: echo "::set-output name=files::$(git diff --name-only origin/${{ github.base_ref }})"

        - name: Search for undesired directives
          continue-on-error: true
          run: |
            strings_to_search=('.. code-block::' '.. code::')
            errors=""  
            for file in ${{ steps.changed_files.outputs.files }}; do  
              if [ -f "$file" ]; then  # Check if file exists  
                for search_string in "${strings_to_search[@]}"; do  
                  if grep -q "$search_string" "$file"; then  
                    errors="$errors\nFound '$search_string' in $file"  
                  fi  
                done  
              fi  
            done  
      
            if [ ! -z "$errors" ]; then  
              echo -e "Errors found:\n$errors"  
              exit 1  
            else  
              echo "No errors found."  
            fi

        - name: Fail if undesired directive is found
          if: failure()
          run: exit 1
