name: Check Code Example Directives

on:
    pull_request:
        paths:
        - "source/**"

jobs:
    search_code_directives:
        runs-on: ubuntu-latest
        steps:
        - name: Check out content from PR
          uses: actions/checkout@v3
          with:  
            fetch-depth: 0
  
        - name: Fetch base branch  
          run: git fetch origin ${{ github.base_ref }} --depth=1 

        - name: Search for undesired directives
          run: |
            errors=""

            plus_lines=$(git diff origin/${{ github.base_ref }}...${{ github.sha }} | grep "^+")

            current_filename=""
            code_block_counter=0
            code_counter=0
            for line in "${plus_lines[@]}"; do
              echo "$line" | grep "^+++" | /dev/null
              if [ $? -eq 0 ] ; then
                if [ $code_block_counter -ne 0 ] || [ $code_counter -ne 0 ] ; then
                  errors="yes"
                  echo "$current_filename contains unsupported code block directives"
                  if [ $code_block_counter -ne 0 ] ; then
                    echo ".. code-block:: appears $code_block_counter times in this file"
                  fi
                  if [ $code_counter -ne 0 ] ; then
                    echo ".. code:: appears $code_counter times in this file"
                  fi
                fi
                current_filename=$(echo "$line" | sed "s/^+++ b\//")
                code_block_counter=0
                code_counter=0
                continue
              fi
              echo "$line" | grep '\.\. code-block::' | /dev/null
              if [ $? -eq 0 ] ; then
                code_block_counter=$((code_block_counter + 1))
                continue
              fi
              echo "$line" | grep '\.\. code::' | /dev/null
              if [ $? -eq 0 ] ; then
                code_counter=$((code_counter + 1))
                continue
              fi
            done
            if [ $code_block_counter -ne 0 ] || [ $code_counter -ne 0 ] ; then
              errors="yes"
              echo "$current_filename contains unsupported code block directives"
              if [ $code_block_counter -ne 0 ] ; then
                echo ".. code-block:: appears $code_block_counter times in this file"
              fi
              if [ $code_counter -ne 0 ] ; then
                echo ".. code:: appears $code_counter times in this file"
              fi
            fi
              
            if [ "$errors" == "yes" ]; then
              echo "Please replace these directives with '.. literalinclude::' or '.. io-code-block::'"          
              exit 1              
            else              
              echo "No errors found."              
            fi
